### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by newtonseple** [newtonseple/eit-pelican#1]
- [ ] Audio hardware
  - [ ] Barryvox connection
  - [ ] Filter
- [ ] Teensy software
  - [ ] Frequency analysis and serial transmitter
- [ ] Middle hardware
  - [ ] USB connection. Drone is host.
- [ ] Drone software   
  - [ ] Sound pattern analysis
  - [ ] Control

- [ ] Check if noise from drone disturbing Barryvox

**Comment by newtonseple** [comment]
implemented as milestone insteadd
